### ISSUE TITLE
Memory leak after updating numba from 0.22.1 to 0.23.1

### ISSUE THREAD

**Issue by takacsd** [numba/numba#1734]
I have some numpy heavy code what I speeded up with numba (no GPU).

It worked beautifully until I updated numba (and a couple of other python packages), after update the mem usage of the code goes up until the OS kills it.
Downgrading numba to the previous version fixed the issue.

I use conda on Ubuntu 14.04 (64 bit).
Good version:
0.22.1-np110py27_0

Bad version:
0.23.1-np110py27_0

**Comment by seibert** [comment]
Would you be willing to try our development packages from Anaconda.org?
```
conda update -c numba numba
```
This would let us know whether or not we already fixed the issue since 0.23.1 was released.

**Comment by bmer** [comment]
I too had the same issue (no GPU), and fixed things by downgrading to
0.22.1, about two weeks ago.

In my case, I was running the latest development version (conda install -c
numba numba, as of two weeks ago), and was still having that trouble.

I'll try and produce a minimal not working example, but...I need a lot of
motivation to do so right now :(

**Comment by seibert** [comment]
OK, good to know.  We have several tests looking for reference leaks, but they obviously don't cover all situations.  Any information you can provide would be appreciated, even if you don't have time for a working example.  :)

**Comment by bmer** [comment]
@seibert  Would you be interested in a copy of my simulation? It is easy to run, and I can remove all the visualization bits, which require other packages (like cairo), so that only numba and numpy are needed.

I started testing things out right now, but then I realized that if I went further, the existing simulations I am running would crash...so, I might have to wait a couple of days before I can really get to it on my computer.

Otherwise, here's my post from a couple of weeks ago, lamenting the memory leaks: https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/OzeAkz9YuPQ

At the time, I wasn't sure what the issue was (I still hadn't downgraded to numba), so I theorize that it might be some other things (such as using 64bit numbers on a machine with only 4GB RAM), but those were not culprit in hindsight.

**Comment by seibert** [comment]
Yes, even a non-minimal case would help us.  Thanks!

**Comment by takacsd** [comment]
I have a minimal test case for you:
```python
import numba
import numpy
import numpy.random

@numba.njit
def evaluate_split(values, split, targets):
    no_targets = targets.shape[0]
    sum = numpy.zeros((49,2), dtype=numpy.float32)

    for i in range(0, no_targets):
        t = targets[i]
        if numpy.int_(values[i, split[0]]) - numpy.int_(values[i, split[1]]) > split[2]:
            sum += t

for i in xrange(0,2000):
    values = numpy.array(numpy.random.randint(0, 255, (10000, 400)), dtype=numpy.uint8)
    split = numpy.array(numpy.random.randint(0,400,3),dtype=numpy.int32)
    targets = numpy.random.rand(10000,49,2)
    evaluate_split(values, split, targets)
    print i
```
(In case you wondering: I removed a lot of irrelevant stuff from the code, so it does not calculate anything meaningful anymore...)

Affected versions: 0.23.1-np110py27_0, 0.23.1-np110py27_214
Not affected version: 0.22.1-np110py27_0

Hope it helps.

**Comment by pitrou** [comment]
Thank you very much for posting this reproducer! I have managed to diagnose the issue and posted a fix in PR #1738.
