### ISSUE TITLE
numba compatibility with Ray

### ISSUE THREAD

**Issue by DarylWM** [numba/numba#4256]
Hello. I'm trying to call a numba-decorated function from a ray.remote function. Without the `@njit(fastmath=True)` decoration the function works fine. With the decoration (I've also tried `@jit` and `@njit` without `fastmath`), I get a fatal error:

`Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass
`

The function is:
```
@njit(fastmath=True)
def mz_centroid(_int_f, _mz_f):
    return ((_int_f/_int_f.sum()) * _mz_f).sum()

```
It works fine as-is when it's called by a normal function (i.e. a function that is not a ray.remote). Am I doing something that should work?

Versions are ray 0.7.1, numba 0.44.1, and Python 3.6.7.

The full stack trace is:
```
Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /opt/concourse/worker/volumes/live/636f0d85-60d4-452d-50e9-ca6ab5111e2d/volume/llvmdev_1560805383854/work/lib/IR/LegacyPassManager.cpp, line 849.
(pid=1124) Fatal Python error: Aborted
(pid=1124) 
(pid=1124) Stack (most recent call first):
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/llvmlite/binding/ffi.py", line 114 in __call__
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/llvmlite/binding/transforms.py", line 88 in _populate_module_pm
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/llvmlite/binding/transforms.py", line 95 in populate
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/targets/codegen.py", line 660 in _module_pass_manager
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/targets/codegen.py", line 627 in _init
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/targets/codegen.py", line 608 in __init__
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/targets/cpu.py", line 49 in init
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/compiler_lock.py", line 32 in _acquire_compile_lock
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/targets/base.py", line 250 in __init__
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/targets/registry.py", line 34 in _toplevel_target_context
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/utils.py", line 381 in __get__
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/targets/registry.py", line 50 in target_context
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 542 in __init__
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/decorators.py", line 177 in wrapper
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/decorators.py", line 161 in jit
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/decorators.py", line 224 in njit
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/typed/typeddict.py", line 18 in <module>
(pid=1124)   File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
(pid=1124)   File "<frozen importlib._bootstrap_external>", line 678 in exec_module
(pid=1124)   File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
(pid=1124)   File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
(pid=1124)   File "<frozen importlib._bootstrap>", line 971 in _find_and_load
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/typed/__init__.py", line 3 in <module>
(pid=1124)   File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
(pid=1124)   File "<frozen importlib._bootstrap_external>", line 678 in exec_module
(pid=1124)   File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
(pid=1124)   File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
(pid=1124)   File "<frozen importlib._bootstrap>", line 971 in _find_and_load
(pid=1124)   File "/Users/fred/anaconda3/envs/py36/lib/python3.6/site-packages/numba/__init__.py", line 41 in <module>
(pid=1124)   File "<frozen importlib._bootstrap>", line 219 in _c

```

**Comment by seibert** [comment]
I don't think we've every tried using Numba with Ray, although Numba functions should work properly with pickle serialization and we do know they work with Dask distributed.

So there's no known reason it shouldn't work, although this looks like something strange is happening with the initialization of LLVM.  We'll have to do some experiments here and see if we can reproduce this.

**Comment by seibert** [comment]
also, just for completeness, can you run the `numba -s` command, which will let us know what platform, CPU features, and optional libraries (like SVML) are present?

**Comment by sklam** [comment]
I can reproduce with:

```python
import numpy as np
from numba import njit
import ray

@njit(fastmath=True)
def mz_centroid(_int_f, _mz_f):
    return ((_int_f/_int_f.sum()) * _mz_f).sum()


@ray.remote
def f():
    a = np.random.random(10)
    b = 123
    return mz_centroid(a, b)


ray.init()
results = ray.get([f.remote() for i in range(4)])
print(results)
```

**Comment by sklam** [comment]
Here's a minimal reproducer:

```python
import ray   # the importing of ray is causing llvm to abort 

from llvmlite import binding as ll
import llvmlite.llvmpy.passes as lp

ll.initialize()
ll.initialize_all_targets()
ll.initialize_all_asmprinters()

pm = ll.create_module_pass_manager()
pmb = lp.create_pass_manager_builder(opt=0)
pmb.populate(pm)
```

**Comment by stuartarchibald** [comment]
Can't seem to reproduce on linux.

**Comment by sklam** [comment]
Related issues: 

* https://github.com/JuliaPy/PyCall.jl/issues/476

Potential workaround:

* https://github.com/JuliaPy/PyCall.jl/issues/679#issuecomment-482419678

**Comment by sklam** [comment]
I am starting to doubt this is a llvmlite problem.  It could be on how ray/pyarrow is loading their LLVM.

**Comment by DarylWM** [comment]
numba -s output

```
--------------------------------------------------------------------------------
__Time Stamp__
2019-07-02 21:03:43.936836

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : haswell
CPU count                                     : 4
CPU Features                                  : 
64bit aes avx avx2 bmi bmi2 cmov cx16 f16c fma fsgsbase invpcid lzcnt mmx movbe
pclmul popcnt rdrnd sahf sse sse2 sse3 sse4.1 sse4.2 ssse3 xsave xsaveopt

__OS Information__
Platform                                      : Darwin-18.6.0-x86_64-i386-64bit
Release                                       : 18.6.0
System Name                                   : Darwin
Version                                       : Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
OS specific info                              : 10.14.5   x86_64

__Python Information__
Python Compiler                               : GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
Python Implementation                         : CPython
Python Version                                : 3.6.7
Python Locale                                 : en_AU UTF-8

__LLVM information__
LLVM version                                  : 8.0.0

__CUDA Information__
CUDA driver library cannot be found or no CUDA enabled devices are present.
Error class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>

__ROC Information__
ROC available                                 : False
Error initialising ROC due to                 : No ROC toolchains found.
No HSA Agents found, encountered exception when searching:
Error at driver init: 

HSA is not currently supported on this platform (darwin).
:

__SVML Information__
SVML state, config.USING_SVML                 : False
SVML library found and loaded                 : False
llvmlite using SVML patched LLVM              : True
SVML operational                              : False

__Threading Layer Information__
TBB Threading layer available                 : True
OpenMP Threading layer available              : True
Workqueue Threading layer available           : True

__Numba Environment Variable Information__
None set.

__Conda Information__
WARNING: The conda.compat module is deprecated and will be removed in a future release.
conda_build_version                           : 3.15.1
conda_env_version                             : 4.6.11
platform                                      : osx-64
python_version                                : 2.7.16.final.0
root_writable                                 : True
WARNING: The conda.compat module is deprecated and will be removed in a future release.

__Current Conda Env__
absl-py                   0.6.1                    pypi_0    pypi
aiohttp                   3.5.4                    pypi_0    pypi
appnope                   0.1.0            py36hf537a9a_0  
asn1crypto                0.24.0                py36_1003    conda-forge
astor                     0.7.1                    pypi_0    pypi
astroid                   2.1.0                    py36_0  
async-timeout             3.0.1                    pypi_0    pypi
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     18.2.0                   pypi_0    pypi
backcall                  0.1.0                    py36_0  
blas                      1.0                         mkl  
bleach                    2.1.3                    py36_0  
boto                      2.49.0                   pypi_0    pypi
boto3                     1.9.144                  pypi_0    pypi
botocore                  1.12.144                 pypi_0    pypi
brain-isotopic-distribution 1.5.3                    pypi_0    pypi
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py36_0  
cffi                      1.11.5           py36h6174b99_1  
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                      pypi_0    pypi
cloudpickle               0.6.1                      py_0    conda-forge
colormath                 3.0.0                    pypi_0    pypi
cryptography              2.4.2            py36ha12b0ac_0  
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.6                   pypi_0    pypi
cytoolz                   0.9.0.1         py36h1de35cc_1001    conda-forge
dash                      0.35.1                   pypi_0    pypi
dash-core-components      0.42.1                   pypi_0    pypi
dash-html-components      0.13.4                   pypi_0    pypi
dash-renderer             0.17.0                   pypi_0    pypi
dash-table                3.1.11                   pypi_0    pypi
dask-core                 1.1.0                      py_0    conda-forge
dbus                      1.13.6               h90a0687_0  
decorator                 4.3.0                    py36_0  
dill                      0.2.9                    pypi_0    pypi
django                    2.1.5                    pypi_0    pypi
django-plotly-dash        0.9.7                    pypi_0    pypi
dpd-components            0.1.0                    pypi_0    pypi
engineering-notation      0.5.2                    pypi_0    pypi
entrypoints               0.2.3            py36hd81d71f_2  
expat                     2.2.6                h0a44026_0  
filelock                  3.0.10                   pypi_0    pypi
filterpy                  1.4.1                    pypi_0    pypi
flask                     1.0.2                    pypi_0    pypi
flask-compress            1.4.0                    pypi_0    pypi
flatbuffers               1.10                     pypi_0    pypi
freetype                  2.9.1                hb4e5f40_0  
funcsigs                  1.0.2                    pypi_0    pypi
gast                      0.2.0                    pypi_0    pypi
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.2               hd9629dc_0  
grpcio                    1.16.0                   pypi_0    pypi
h5py                      2.8.0                    pypi_0    pypi
hdf5                      1.10.2               hfa1e0ec_1  
html5lib                  1.0.1            py36h2f9c1c0_0  
icu                       58.2                 h4b95b61_1  
idna                      2.8                   py36_1000    conda-forge
idna-ssl                  1.1.0                    pypi_0    pypi
imageio                   2.4.1                 py36_1000    conda-forge
intel-openmp              2019.0                      118  
ipydatawidgets            4.0.0                      py_0    conda-forge
ipykernel                 5.1.0            py36h39e3cac_0  
ipyscales                 0.3.0                      py_0    conda-forge
ipython                   6.4.0                    py36_0  
ipython_genutils          0.2.0            py36h241746c_0  
ipyvolume                 0.5.1                 py36_1001    conda-forge
ipywebrtc                 0.4.3                 py36_1000    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.4                    py36_0  
itsdangerous              1.1.0                    pypi_0    pypi
jedi                      0.12.0                   py36_1  
jinja2                    2.10             py36hd36f9c5_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py36hb385e00_0  
jupyter                   1.0.0                    py36_7  
jupyter-console           6.0.0                    pypi_0    pypi
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0                    py36_1  
jupyter_core              4.4.0            py36h79cf704_0  
keras-applications        1.0.6                    pypi_0    pypi
keras-preprocessing       1.0.5                    pypi_0    pypi
kiwisolver                1.0.1                    pypi_0    pypi
lazy-object-proxy         1.3.1            py36h1de35cc_2  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.35               ha441bb4_0  
libsodium                 1.0.16               h3efe00b_0  
libtiff                   4.0.9                hcb84e12_2  
line-profiler             2.1.2                    pypi_0    pypi
llvmlite                  0.28.0                   pypi_0    pypi
lxml                      4.3.3                    pypi_0    pypi
markdown                  3.0.1                    pypi_0    pypi
markupsafe                1.0              py36h3a1e703_1  
matplotlib                2.2.2                    pypi_0    pypi
matplotlib-base           3.0.2           py36hf043ca5_1001    conda-forge
mccabe                    0.6.1                    py36_1  
mistune                   0.8.3            py36h1de35cc_1  
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36h1de35cc_1    conda-forge
mkl_random                1.0.2            py36h1702cab_2    conda-forge
more-itertools            7.0.0                    pypi_0    pypi
ms-deisotope              0.0.9                    pypi_0    pypi
ms-peak-picker            0.1.25                   pypi_0    pypi
multidict                 4.5.2                    pypi_0    pypi
nbconvert                 5.3.1            py36h810822e_0  
nbformat                  4.4.0            py36h827af21_0  
nbserverproxy             0.8.8                    pypi_0    pypi
ncurses                   6.1                  h0a44026_0  
networkx                  2.2                        py_1    conda-forge
ninja                     1.8.2            py36h04f5b5a_1  
notebook                  5.7.4                    py36_0  
numba                     0.38.1                   pypi_0    pypi
numpy                     1.14.3                   pypi_0    pypi
numpy-base                1.15.4           py36h6575580_0  
olefile                   0.46                     py36_0  
openssl                   1.1.1c               h1de35cc_1  
pandas                    0.23.0                   pypi_0    pypi
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py36h3b0b094_1  
parso                     0.2.0                    py36_0  
pcre                      8.42                 h378b8a2_0  
peakutils                 1.3.2                    pypi_0    pypi
pexpect                   4.5.0                    py36_0  
pickleshare               0.7.4            py36hf512f8e_0  
pillow                    5.4.1            py36hb68e598_0  
pip                       19.1.1                   pypi_0    pypi
plotly                    3.5.0                    pypi_0    pypi
pluggy                    0.9.0                    pypi_0    pypi
prometheus_client         0.5.0                    py36_0  
prompt-toolkit            1.0.15                   pypi_0    pypi
protobuf                  3.6.1                    pypi_0    pypi
psims                     0.1.25                   pypi_0    pypi
psutil                    5.6.1                    pypi_0    pypi
ptyprocess                0.5.2            py36he6521c3_0  
py                        1.8.0                    pypi_0    pypi
py-spy                    0.1.10                   pypi_0    pypi
pyarrow                   0.13.0                   pypi_0    pypi
pycparser                 2.19                     py36_0  
pygments                  2.2.0            py36h240cd3f_0  
pylint                    2.2.2                    py36_0  
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.2.0                    pypi_0    pypi
pyqt                      5.9.2            py36h655552a_2  
pysocks                   1.6.8                 py36_1002    conda-forge
pyteomics                 4.1                      pypi_0    pypi
pytest                    4.4.1                    pypi_0    pypi
python                    3.6.7                haf84260_0  
python-dateutil           2.7.3                    py36_0  
python.app                2                        py36_9  
pythreejs                 2.0.2                 py36_1000    conda-forge
pytorch                   0.4.1           py36_cuda0.0_cudnn0.0_1    pytorch
pytz                      2018.4                   pypi_0    pypi
pywavelets                1.0.1           py36h917ab60_1000    conda-forge
pyzmq                     17.0.0           py36h1de35cc_1  
qt                        5.9.6                h45cd832_2  
qtconsole                 4.4.3                    pypi_0    pypi
ray                       0.7.1                    pypi_0    pypi
readline                  7.0                  hc1231fa_4  
redis                     3.2.1                    pypi_0    pypi
requests                  2.21.0                py36_1000    conda-forge
retrying                  1.3.3                    pypi_0    pypi
scikit-image              0.14.0                   pypi_0    pypi
scikit-learn              0.19.1                   pypi_0    pypi
scipy                     1.1.0                    pypi_0    pypi
send2trash                1.5.0                    py36_0  
setproctitle              1.1.10                   pypi_0    pypi
setuptools                39.1.0                   py36_0  
simplegeneric             0.8.1                    py36_2  
sip                       4.19.8           py36h0a44026_0  
six                       1.11.0           py36h0e22d5e_1  
sklearn                   0.0                      pypi_0    pypi
sqlalchemy                1.3.1                    pypi_0    pypi
sqlite                    3.25.2               ha441bb4_0  
tensorboard               1.12.0                   pypi_0    pypi
tensorflow                1.12.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h625a49b_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.9.0                      py_1    conda-forge
torchvision               0.2.1                    py36_1    pytorch
tornado                   5.0.2                    py36_0  
traitlets                 4.3.2            py36h65bd3ce_0  
traittypes                0.2.1                      py_1    conda-forge
typed-ast                 1.1.0            py36h1de35cc_0  
typing                    3.6.6                    pypi_0    pypi
typing-extensions         3.7.2                    pypi_0    pypi
urllib3                   1.24.1                py36_1000    conda-forge
wcwidth                   0.1.7            py36h8c6ec74_0  
webencodings              0.5.1            py36h3b9701d_1  
werkzeug                  0.14.1                   pypi_0    pypi
wheel                     0.31.1                   py36_0  
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wrapt                     1.11.0           py36h1de35cc_0  
xz                        5.2.4                h1de35cc_4  
yarl                      1.3.0                    pypi_0    pypi
zeromq                    4.2.5                h378b8a2_0  
zlib                      1.2.11               hf3cbc9b_2  
--------------------------------------------------------------------------------

```

**Comment by DarylWM** [comment]
Hi @sklam - thanks for the link to the Julia issue - not sure how to try the possible workaround of pre-loading gandiva.so mentioned there - can't find gandiva.so on this system.

**Comment by DarylWM** [comment]
Tried the same code on Ubuntu 18.04 and it works fine.

**Comment by seibert** [comment]
Hmm, I wonder if this has to do with differences in the way Linux and macOS handle linking and symbol resolution.

**Comment by olivierlefloch** [comment]
I can reproduce this on Mac OS 10.14.5, with python 3.7.2, with `ray-0.7.2` and `numba-0.45.0`:

```
import ray
import numba
```

fails with

```
Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /Users/buildbot/miniconda3/conda-bld/llvmdev_1556270736866/work/lib/IR/LegacyPassManager.cpp, line 849.
```

Importing `numba` first, then `ray` does not fail in the same way. And importing `numba` before importing `ray` also makes @sklam 's minimal reproduction case pass.

I'll look into opening a bug with https://github.com/ray-project/ray

**Comment by robertnishihara** [comment]
As mentioned in https://github.com/ray-project/ray/issues/5250#issuecomment-514066458, I can reproduce the issue on MacOS 10.14.3 with Python 3.6.7, by doing

```
import pyarrow
import numba
```

Since ray uses pyarrow (ray actually vendors its own version of pyarrow, but I can reproduce the issue with the pyarrow release on PyPI), I suspect the issue has to do with how Arrow bundles llvm.

**Comment by robertnishihara** [comment]
FYI @wesm @pravindra.

**Comment by wesm** [comment]
Please take up with the Arrow dev mailing list

**Comment by igozali** [comment]
For the benefit of people looking into the numba & pyarrow compatibility issue and are not subscribed to the Arrow dev mailing list, I got in touch with Wes via said mailing list, copying his reply verbatim below.

> hi Ivan,
> 
> We have statically linked LLVM symbols in our wheels on all platforms.
> We're looking for new maintainers for the wheels to take care of
> issues like this, see [1]. In the meantime, I suggest you use conda
> packages if you need to use numba and pyarrow together.
> 
> Thanks
> 
> [1]: https://lists.apache.org/thread.html/128a2bec285ad45aa4189ebb39a15b39dcf6d91c4ab0278ff4f7cdea@%3Cdev.arrow.apache.org%3E

Few workarounds I have:
- install `pyarrow==0.12.1`, which works with the latest `numba==0.45.0` at the time of writing.
- as suggested above, use conda packages if you need to use numba and pyarrow together

**Comment by robertnishihara** [comment]
Thanks @igozali. That should address arrow + numba, but won't quite solve the issue of ray + numba because ray actually ships with its own pyarrow wheels (as opposed to depending on the ones in PyPI). The reason for that has to do with needing to build pyarrow wheels that are compatible with TensorFlow and PyTorch (there is a longer discussion detailed in https://groups.google.com/forum/#!topic/ray-dev/gbYKK9Gy_ns/discussion).

**Comment by vfilimonov** [comment]
One more workaround: I don't use ray, but with the plain `pyarrow` (version 15.0) it looks like the order of imports matter.

I.e. this will crash
```python
import pyarrow
import numba
```
And this will work
```python
import numba
import pyarrow
```

I'm not aware of side effects though.

**Comment by wesm** [comment]
This should be fixed in 0.15.1 (out soon)

**Comment by stuartarchibald** [comment]
Thanks @wesm, presume https://github.com/numba/numba/issues/4751 is fixed by the same?

**Comment by wesm** [comment]
Yes

**Comment by vfilimonov** [comment]
Just for the information: pyarrow 0.15.1 was released on November 1, 2019 - and with newer version 
there's no conflicts numba and pyarrow:
```python
import pyarrow
import numba
```
works equally fine as the opposite order.

As @robertnishihara mentioned that Ray ships its own pyarrow:
> Thanks @igozali. That should address arrow + numba, but won't quite solve the issue of ray + numba because ray actually ships with its own pyarrow wheels (as opposed to depending on the ones in PyPI). The reason for that has to do with needing to build pyarrow wheels that are compatible with TensorFlow and PyTorch (there is a longer discussion detailed in https://groups.google.com/forum/#!topic/ray-dev/gbYKK9Gy_ns/discussion).

So maybe the issue (if still exists) now belongs to Ray repository rather than numba's?

**Comment by robertnishihara** [comment]
This is fixed in the latest master (not the latest release yet). You can try installing the latest wheels by following the instructions at https://ray.readthedocs.io/en/latest/installation.html#latest-snapshots-nightlies.

**Comment by stuartarchibald** [comment]
@robertnishihara thanks for confirming the fix, please could you ping when the release with the fix in is shipped so that this ticket can be closed. Many thanks in advance!

**Comment by robertnishihara** [comment]
@vfilimonov, this is fixed now in ray==0.8.2. The example posted by @sklam works now.

**Comment by stuartarchibald** [comment]
Thanks for all the fixes folks, seems like the last item was fixed in ray=0.8.2.

Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
