### ISSUE TITLE
"cannot import name '_typeconv' from 'numba.core.typeconv'"

### ISSUE THREAD

**Issue by Eheran1** [numba/numba#6973]
Im using Anaconda Navigator and Spyder "inside" that. The "base" environment comes with numba installed, however, failes multiple ways no matter what I do. So I made a new environment "Test" and installed numba via cmd promt as explained here: [https://anaconda.org/numba/numba](url)
`conda install -c numba numba `

Then in Spyder try to run:
`import numba`

I tryed updating (anaconda navigator, conda, spyder, numba), reinstalling (anaconda navigator, numba, updates this and that way, uninstall->install, force install; so a buch of stuff found via google)
I still get the error below. In the "base" environment I had a few other errors (like "OSError: Could not load shared object file: llvmlite.dll") over the course of trying to get numba running, but its the same import _typeconv now.

Oh and I did find a at least 2 issues like this, closed, but with no solution (that works for me).

```
C:\ProgramData\**Anaconda3**\envs\Test\python.exe
**Python version 3.8.8** | packaged by **conda-forge** | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)]
sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
Traceback (most recent call last):

  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv

ImportError: cannot import name '_typeconv' from 'numba.core.typeconv' (C:\Users\***\AppData\Roaming\Python\Python38\site-packages\numba\core\typeconv\__init__.py)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\***\.spyder-py3\temp.py", line 14, in <module>
    import numba

  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\numba\__init__.py", line 24, in <module>
    from numba.misc.special import (

  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof

  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context

  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules

  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules

  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))

ImportError: Numba could not be imported.

[not development, blabla cut out] 

The original error was: 'cannot import name '_typeconv' from 'numba.core.typeconv' (C:\Users\***\AppData\Roaming\Python\Python38\site-packages\numba\core\typeconv\__init__.py)'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\ProgramData\Anaconda3\envs\Test\python.exe
```

**Comment by stuartarchibald** [comment]
Thanks for the report. To try and isolate the problem, have you tried using the windows command prompt to create a new environment and then installing Numba into that and seeing if it works?

**Comment by chrisk314** [comment]
I'm hitting this issue as well on Windows 10 with python3.7 installing numba (latest version 0.53.1) in a virtual environment with pip. See steps below in PowerShell. Note that I have installed the latest Visual C++ Redistributable as suggested in #5600 and I also attemped rolling back to 0.49.0 (also suggested in #5600) neither of which helped.

```
PS C:\Users\cknight\src> python -m venv .venv
PS C:\Users\cknight\src> .venv\Scripts\activate
(.venv) PS C:\Users\cknight\src> python -m pip install -U pip
Collecting pip
  Using cached pip-21.1.1-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-21.1.1
(.venv) PS C:\Users\cknight\src> python -m pip install numba
Collecting numba
  Downloading numba-0.53.1-cp37-cp37m-win_amd64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 2.2 MB/s
Collecting numpy>=1.15
  Downloading numpy-1.20.2-cp37-cp37m-win_amd64.whl (13.6 MB)
     |████████████████████████████████| 13.6 MB ...
Requirement already satisfied: setuptools in c:\users\cknight\src\.venv\lib\site-packages (from numba) (47.1.0)
Collecting llvmlite<0.37,>=0.36.0rc1
  Downloading llvmlite-0.36.0-cp37-cp37m-win_amd64.whl (16.0 MB)
     |████████████████████████████████| 16.0 MB 6.4 MB/s
Installing collected packages: numpy, llvmlite, numba
Successfully installed llvmlite-0.36.0 numba-0.53.1 numpy-1.20.2
(.venv) PS C:\Users\cknight\src> python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
Traceback (most recent call last):
  File "C:\Users\cknight\src\.venv\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cknight\src\.venv\lib\site-packages\numba\__init__.py", line 24, in <module>
    from numba.misc.special import (
  File "C:\Users\cknight\src\.venv\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\Users\cknight\src\.venv\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\Users\cknight\src\.venv\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "C:\Users\cknight\src\.venv\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\Users\cknight\src\.venv\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide https://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: The specified module could not be found.'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Users\cknight\src\.venv\Scripts\python.exe

>>>
```

**Comment by chrisk314** [comment]
I have temporarily fixed my issue by pinning dependencies as follows: `llvmlite==0.32.1`, `numba==0.47.0`.

**Comment by Fngg** [comment]
python -m pip uninstall numba
python -m pip install numba==0.47.0

**Comment by esc** [comment]
Thank you everyone for commenting on this issue. Since the OP @Eheran1 never replied back I am assuming this issue is resolved and will now close it.

As a remark: the error `ImportError: cannot import name '_typeconv' from 'numba.core.typeconv'` is usually the result of a failed update procedure by `pip`. Numba was changed significantly from 0.47 to 0.48 with a large number of internal refactoring. Essentially what happened, was that the `_typeconv` was moved to `numba.core`. We had found that during the update `pip` would not cleanly deinstall older versions, so two very different versions of Numba had become conflated leading to this specific error.  We had seen this error very frequently after the refactoring and the fix for almost all the occurrences was to setup a fresh virtualenv and install `numba` again. This is probably also why the recommendation to install or re-install version `0.47.0` seems to help some users.

Hope this helps!

**Comment by Eheran1** [comment]
I have not tried to use numba since, thus no update from me since I have nothing new to add.

**Comment by esc** [comment]
> I have not tried to use numba since, thus no update from me since I have nothing new to add.

OK, well, do feel free to re-open, or make a new issue, in case the issue does persist.

**Comment by gjain75** [comment]
> Thanks for the report. To try and isolate the problem, have you tried using the windows command prompt to create a new environment and then installing Numba into that and seeing if it works?

I have the same problem, tried creating a completely new environment with required dependencies, still throws same error

**Comment by esc** [comment]
> > Thanks for the report. To try and isolate the problem, have you tried using the windows command prompt to create a new environment and then installing Numba into that and seeing if it works?
> 
> I have the same problem, tried creating a completely new environment with required dependencies, still throws same error

Thank you. As stated previously, this error message is almost certainly caused by an older release of Numba "sticking" around somehow (probably a bug).

We will be more than happy to debug this for you. Please open a new issue for your case. In order to debug, we will need:

a) The commands you entered and what they output.
b) A description of what you expected to happen
c) What did happen instead

Thank you.
